export enum ETequilaLangueCode {
  "ar-AE" = "ar-AE",
  "cs-CZ" = "cs-CZ",
  "da-DK" = "da-DK",
  "de-DE" = "de-DE",
  "el-GR" = "el-GR",
  "en-US" = "en-US",
  "es-ES" = "es-ES",
  "fi-FI" = "fi-FI",
  "fr-FR" = "fr-FR",
  "hu-HU" = "hu-HU",
  "is-IS" = "is-IS",
  "it-IT" = "it-IT",
  "iw-IL" = "iw-IL",
  "ja-JP" = "ja-JP",
  "ko-KR" = "ko-KR",
  "lt-LT" = "lt-LT",
  "ms-MY" = "ms-MY",
  "nl-NL" = "nl-NL",
  "no-NO" = "no-NO",
  "pl-PL" = "pl-PL",
  "pt-BR" = "pt-BR",
  "pt-PT" = "pt-PT",
  "ro-RO" = "ro-RO",
  "ru-RU" = "ru-RU",
  "sk-SK" = "sk-SK",
  "sr-RS" = "sr-RS",
  "sv-SE" = "sv-SE",
  "th-TH" = "th-TH",
  "tr-TR" = "tr-TR",
  "uk-UA" = "uk-UA",
  "zh-CN" = "zh-CN",
  "zh-TW" = "zh-TW",
}

export enum ETequilaLocationType {
  station = "station",
  airport = "airport",
  bus_station = "bus_station",
  city = "city",
  autonomous_territory = "autonomous_territory",
  subdivision = "subdivision",
  country = "country",
  region = "region",
  continent = "continent",
}
export enum EEngagementMetricTequilaType {
  searches = "searches",
  bookings = "bookings",
  clicks = "clicks",
}
